spring:
  application:
    name: test
server:
  port: 9999
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8100/eureka/
data:
  message: testtesttest
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

